---
title: "Proje Rapor : PINAR NUR ÖZTÜRK 210401058" 
output:
  html_document:
    df_print: paged
    
lang: tr
---

# Q1 : Problem tanımı

Şirketimiz **Green Consulting**. Problemimiz *günümüzde çevre kirliliği faktörleri ile nüfus artışı arasındaki karmaşık ilişki, çevresel politikaların etkin bir şekilde yönlendirilmesini zorlaştırmaktadır. Green Consulting, bu karmaşıklığı anlamak ve çevresel politikalar üzerindeki etkisini belirleyerek sürdürülebilir bir geleceği şekillendirmeyi amaçlamaktadır.*

# Q2 : Proje Amacı
**Çevre Kirliliği ve Nüfus Artışı İlişkisinin Analizi: Sürdürülebilir Geleceği Şekillendirmek** [world-polluted-country-report](https://www.kaggle.com/datasets/rafsunahmad/world-polluted-country-report) ve [World Population Dataset](https://www.kaggle.com/datasets/iamsouravbanerjee/world-population-dataset) adlı Kaggle veri setlerini kullandığımız bu projenin temel amacı, *çevre kirliliği faktörleri ile nüfus artışı arasındaki karmaşık ilişkiyi anlamak ve bu ilişkinin çevresel politikalara etkisini belirlemektir.* Bu kapsamda, dünya genelindeki çevre kirliliği verilerini analiz ederek, çevre kirliliği ile nüfus artışı arasındaki ilişkiyi **kwantitatif** bir şekilde ortaya koymayı hedefliyoruz. Analiz etapları arasında, çevre kirliliği faktörlerini belirleme, nüfus artışı ile bu faktörler arasındaki ilişkiyi değerlendirme ve çevresel politikalara önerilerde bulunma yer almaktadır.Bu analizlerden elde edilen sonuçlar, çevre kirliliği ve nüfus artışı arasındaki ilişkinin derinlemesine anlaşılmasına katkı sağlayacak ve çevresel politikaların daha etkin bir şekilde yönlendirilmesine olanak tanıyacaktır. Ayrıca, sürdürülebilir bir geleceği şekillendirmek için önerilecek çözümler, çevresel sürdürülebilirlik alanında kritik öneme sahip olacaktır.
